source "https://rubygems.org/"


# Web
gem "sinatra"
gem 'puma'
gem 'nio4r', '~> 2.5'

# Service
gem 'trailblazer-operation'

# Debug
gem 'pry'
# gem 'debugger'

#
# source "https://rubygems.org"
#
# gem 'httparty'
# gem 'nokogiri'
gem 'byebug'
# gem 'pry', '~> 0.12.2'
gem 'rubocop-performance'
# gem 'puma'
gem 'trailblazer-operation'
gem 'rack-cors'
# gem 'foreman'

# test
gem 'rspec'
